# Generated by Django 6.0.5 on 2026-05-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('value', models.TextField(default='')),
                ('category', models.CharField(choices=[('financial', 'Financial'), ('business', 'Business Info'), ('incentive', 'Staff & Incentive'), ('operations', 'Operations')], default='financial', max_length=50)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('percent', 'Percent'), ('email', 'Email'), ('tel', 'Phone'), ('textarea', 'Textarea'), ('select', 'Select')], default='text', max_length=20)),
                ('options', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'id'],
            },
        ),
    ]
