# Generated by Django 6.0.5 on 2026-05-12 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('employees', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_card_number', models.CharField(max_length=255, unique=True)),
                ('job_card_date', models.DateField()),
                ('vehicle_kilometers', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle_entry_time', models.DateTimeField()),
                ('vehicle_exit_time', models.DateTimeField(blank=True, null=True)),
                ('job_card_status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=50)),
                ('complaints', models.TextField(blank=True, null=True)),
                ('customer_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customerasset')),
            ],
        ),
        migrations.CreateModel(
            name='JobCardService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_card_services', to='jobcards.jobcard')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='JobCardEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee')),
                ('job_card_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='jobcards.jobcardservice')),
            ],
        ),
    ]
