# Generated by Django 6.0.5 on 2026-05-25 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_advance_salary_month_transaction_incentive_incentivesetting'),
        ('jobcards', '0003_jobcard_gst_percent_jobcardpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.employee'),
        ),
    ]
