# Generated by Django 6.0.5 on 2026-05-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0004_jobcard_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcardservice',
            name='service_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In_Progress', 'In Progress'), ('completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
