# Generated by Django 6.0.5 on 2026-05-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0005_jobcardservice_service_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcardservice',
            name='service_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
