# Generated by Django 6.0.5 on 2026-05-26 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0007_alter_jobcardservice_service_status'),
        ('services', '0002_remove_serviceproduct_quantity_required'),
        ('vendors', '0008_alter_inventory_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCardProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_card_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='jobcards.jobcardservice')),
                ('service_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.serviceproduct')),
            ],
        ),
        migrations.CreateModel(
            name='JobCardProductUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_card_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='jobcards.jobcardproduct')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendors.inventory')),
            ],
        ),
    ]
