# Generated by Django 6.0.5 on 2026-05-27 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0008_jobcardproduct_jobcardproductusage'),
        ('services', '0002_remove_serviceproduct_quantity_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcardproduct',
            name='service_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.serviceproduct'),
        ),
    ]
