# Generated by Django 6.0.5 on 2026-06-29 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0020_jobcard_share_token'),
        ('jobcards', '0020_salesorder_total_amount'),
    ]

    operations = [
    ]
