# Generated by Django 6.0.5 on 2026-07-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='trigger_type',
            field=models.CharField(choices=[('job_checkin', 'Job Check-in'), ('job_completed', 'Job Completed'), ('service_complete', 'Service Complete'), ('payment_received', 'Payment Received'), ('customer_welcome', 'Customer Welcome'), ('garage_payment', 'Garage Payment'), ('service_reminder', 'Service Reminder'), ('service_due_today', 'Service Due Today'), ('garage_all_completed', 'Garage All Completed'), ('low_stock_alert', 'Low Stock Alert'), ('salary_processed', 'Salary Processed'), ('member_absent', 'Member Absent')], max_length=50),
        ),
    ]
