# Generated by Django 6.0.5 on 2026-05-09 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceemployee',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='services.service'),
        ),
        migrations.AlterField(
            model_name='serviceproduct',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='services.service'),
        ),
    ]
