# Generated by Django 6.0.5 on 2026-05-26 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceproduct',
            name='quantity_required',
        ),
    ]
