# Generated by Django 6.0.5 on 2026-06-15 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_warranty'),
        ('vendors', '0012_invoiceitem_product_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.product'),
        ),
    ]
