# Generated by Django 6.0.5 on 2026-06-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_serviceproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='four_wheeler_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='other_wheeler_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='two_wheeler_service',
            field=models.BooleanField(default=False),
        ),
    ]
