# Generated by Django 6.0.5 on 2026-05-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_refactor_inventory_invoice_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='minimum_threshold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity_available',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
