# Generated by Django 6.0.5 on 2026-05-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_invoicepayment_payment_method'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='unit_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'brand', 'unit_amount', 'cost_price')},
        ),
    ]
