# Generated by Django 6.0.5 on 2026-06-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
