# Generated by Django 6.0.5 on 2026-08-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0005_alter_estimation_vehicle_sub_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimation',
            name='vehicle_name',
        ),
        migrations.AlterField(
            model_name='estimation',
            name='vehicle_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
