# Generated by Django 6.0.5 on 2026-05-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='late_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='worked_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='shift',
            name='late_grace_minutes',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='shift',
            name='overtime_threshold_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('leave', 'Leave'), ('late', 'Late'), ('overtime', 'Overtime'), ('late_overtime', 'Late + Overtime'), ('auto_absent', 'Auto Absent')], default='present', max_length=20),
        ),
    ]
