# Generated by Django 6.0.5 on 2026-05-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerasset',
            name='vehicle_type',
            field=models.CharField(choices=[('two_wheeler', 'Two Wheeler'), ('four_wheeler', 'Four Wheeler'), ('three_wheeler', 'Three Wheeler'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
