# Generated by Django 6.0.5 on 2026-05-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customerasset_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerasset',
            name='last_service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerasset',
            name='next_service_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
