# Generated by Django 6.0.5 on 2026-08-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garageowner',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
